-- ============================================================================
-- Tickets — a fila de pedidos da lideranca para quem desenvolve
-- ============================================================================
--
-- ## O problema
--
-- Trocar senha, corrigir acordo, investigar erro, liberar acesso: os pedidos
-- chegavam por WhatsApp, cada um em uma conversa, e a fila real so existia na
-- cabeca de duas pessoas. Nao havia estado ("ja estao vendo?"), nao havia
-- historico ("o que decidimos daquela vez?") e nao havia dono.
--
-- ## O desenho
--
-- Um ticket tem SETOR (o de quem abriu), CATEGORIA e ESTADO. Quem abre e a
-- lideranca; quem resolve e uma lista curta e explicita — administradores por
-- padrao, mais quem for autorizado em `tickets_atendentes`.
--
--   aberto -> em_andamento -> concluido
--                 |    \-----> pendente (esperando algo de quem abriu)
--                 \---------> recusado
--   cancelado: so quem abriu, e so enquanto nao estiver concluido/recusado.
--
-- ## Quem ve o que
--
--   * quem abriu ......... o proprio ticket, sempre;
--   * lideranca do setor . todos os tickets DO SETOR dela (o pedido de um lider
--                          do Play 5 e assunto da lideranca do Play 5 inteira);
--   * diretoria .......... todos os setores, sem poder atender;
--   * atendentes ......... tudo, e sao os unicos que mudam estado e assumem.
--
-- Nao ha travar o chat em duas pessoas, como na Ouvidoria: quem enxerga o
-- ticket fala nele. Foi pedido assim — o assunto e da lideranca do setor, nao
-- de um individuo.
--
-- ## A aba nasce fechada
--
-- `tickets_config.liberado_para_lideranca` comeca FALSE: no primeiro dia so
-- administrador ve a aba, para conferir em producao com dados de verdade antes
-- de a lideranca inteira entrar. O botao que vira a chave fica na propria aba.
--
-- ## Notificacao mora no banco
--
-- Os gatilhos abaixo escrevem em `notificacoes`. Poderiam viver no cliente,
-- como em outras telas — e ai uma aba fechada no meio da acao deixaria alguem
-- sem aviso, e um INSERT feito por outro caminho nao avisaria ninguem. Como
-- SECURITY DEFINER no gatilho, a regra vale para toda escrita, venha de onde
-- vier. As regras, uma por uma:
--
--   * ticket novo ........ avisa todos os atendentes (menos quem abriu);
--   * mensagem ........... avisa quem abriu e quem assumiu (menos o autor);
--   * mudanca de estado .. avisa quem abriu e quem assumiu (menos o autor).
--
-- E por isso que um administrador que ainda nao assumiu o ticket nao recebe
-- notificacao de cada mensagem: ele recebeu a de abertura, e o resto e ruido
-- ate ele decidir que aquele ticket e dele.
-- ============================================================================

-- ── Tabelas ─────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.tickets (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Numero curto para as pessoas conversarem ("o 42 ja saiu?"). Sequencia
  -- global de propriedade da coluna: por empresa exigiria serializar os
  -- INSERTs, e o ganho seria estetico.
  numero         BIGINT GENERATED BY DEFAULT AS IDENTITY,
  empresa_id     UUID NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
  -- Setor de quem abriu, CONGELADO no momento da abertura: o pedido continua
  -- sendo do Play 5 mesmo depois de a pessoa mudar de setor.
  setor_id       UUID REFERENCES public.setores(id) ON DELETE SET NULL,
  aberto_por     UUID NOT NULL REFERENCES public.perfis(id) ON DELETE CASCADE,
  -- Copias do nome: a lista abre sem JOIN e sobrevive a exclusao do perfil.
  aberto_por_nome TEXT,
  categoria      TEXT NOT NULL,
  assunto        TEXT NOT NULL,
  descricao      TEXT,
  prioridade     TEXT NOT NULL DEFAULT 'normal'
                 CHECK (prioridade IN ('baixa','normal','alta','urgente')),
  status         TEXT NOT NULL DEFAULT 'aberto'
                 CHECK (status IN ('aberto','em_andamento','pendente','concluido','recusado','cancelado')),
  responsavel_id   UUID REFERENCES public.perfis(id) ON DELETE SET NULL,
  responsavel_nome TEXT,
  -- Campos extras da categoria (usuario citado, aba com erro, NR...). JSONB
  -- porque o conjunto muda com a categoria e todos sao opcionais — uma coluna
  -- por campo viraria uma tabela larga e quase toda nula.
  campos         JSONB NOT NULL DEFAULT '{}'::JSONB,
  criado_em      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  atualizado_em  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  fechado_em     TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_tickets_empresa_status ON public.tickets(empresa_id, status);
CREATE INDEX IF NOT EXISTS idx_tickets_setor          ON public.tickets(setor_id);
CREATE INDEX IF NOT EXISTS idx_tickets_aberto_por     ON public.tickets(aberto_por);
CREATE INDEX IF NOT EXISTS idx_tickets_criado_em      ON public.tickets(criado_em DESC);

CREATE TABLE IF NOT EXISTS public.tickets_mensagens (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id  UUID NOT NULL REFERENCES public.tickets(id) ON DELETE CASCADE,
  autor_id   UUID REFERENCES public.perfis(id) ON DELETE SET NULL,
  autor_nome TEXT,
  autor_foto TEXT,
  texto      TEXT,
  -- [{ url, nome, tipo, tamanho }]. O arquivo vive no bucket `tickets`; aqui
  -- fica so o endereco, para a mensagem carregar sem uma segunda consulta.
  anexos     JSONB NOT NULL DEFAULT '[]'::JSONB,
  criado_em  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (COALESCE(TRIM(texto), '') <> '' OR jsonb_array_length(anexos) > 0)
);

CREATE INDEX IF NOT EXISTS idx_tickets_msg_ticket ON public.tickets_mensagens(ticket_id, criado_em);

-- Trilha do ticket. Escrita SO por gatilho: um historico que depende de o
-- cliente lembrar de gravar e um historico com buracos.
CREATE TABLE IF NOT EXISTS public.tickets_eventos (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id  UUID NOT NULL REFERENCES public.tickets(id) ON DELETE CASCADE,
  autor_id   UUID,
  autor_nome TEXT,
  tipo       TEXT NOT NULL,
  de         TEXT,
  para       TEXT,
  criado_em  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tickets_ev_ticket ON public.tickets_eventos(ticket_id, criado_em);

-- Quem, alem dos administradores, pode atender.
CREATE TABLE IF NOT EXISTS public.tickets_atendentes (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id UUID NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
  perfil_id  UUID NOT NULL REFERENCES public.perfis(id) ON DELETE CASCADE,
  criado_por UUID,
  criado_em  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (empresa_id, perfil_id)
);

CREATE TABLE IF NOT EXISTS public.tickets_config (
  empresa_id UUID PRIMARY KEY REFERENCES public.empresas(id) ON DELETE CASCADE,
  liberado_para_lideranca BOOLEAN NOT NULL DEFAULT FALSE,
  atualizado_por UUID,
  atualizado_em  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── Quem pode atender ───────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.fn_ticket_pode_atender()
RETURNS BOOLEAN
LANGUAGE SQL STABLE SECURITY DEFINER SET search_path TO 'public'
AS $$
  SELECT public.fn_user_is_super_admin()
      OR public.fn_user_has_any_role(ARRAY['administrador'])
      OR EXISTS (
           SELECT 1 FROM public.tickets_atendentes a
            WHERE a.perfil_id = (SELECT auth.uid())
         );
$$;

COMMENT ON FUNCTION public.fn_ticket_pode_atender() IS
  'Administrador e super_admin sempre; os demais, so se estiverem em tickets_atendentes.';

CREATE OR REPLACE FUNCTION public.fn_ticket_visivel(
  p_empresa_id UUID, p_setor_id UUID, p_aberto_por UUID
)
RETURNS BOOLEAN
LANGUAGE SQL STABLE SECURITY DEFINER SET search_path TO 'public'
AS $$
  SELECT public.fn_can_access_empresa(p_empresa_id)
     AND (
          p_aberto_por = (SELECT auth.uid())
       OR public.fn_ticket_pode_atender()
       -- Diretoria enxerga todos os setores, sem atender.
       OR public.fn_user_has_any_role(ARRAY['diretoria'])
       -- Lideranca: o proprio setor, e so ele.
       OR (public.fn_user_has_any_role(ARRAY['lider','elite','gerencia','ouvidoria'])
           AND p_setor_id IS NOT DISTINCT FROM public.fn_user_setor_id())
     );
$$;

-- Quem abre: lideranca para cima. Operador nao abre ticket — o pedido dele
-- passa pelo lider, que e quem tem o contexto.
CREATE OR REPLACE FUNCTION public.fn_ticket_pode_abrir()
RETURNS BOOLEAN
LANGUAGE SQL STABLE SECURITY DEFINER SET search_path TO 'public'
AS $$
  SELECT public.fn_user_is_super_admin()
      OR public.fn_user_has_any_role(
           ARRAY['lider','elite','gerencia','diretoria','administrador','ouvidoria']
         );
$$;

-- ── RLS ─────────────────────────────────────────────────────────────────────

ALTER TABLE public.tickets            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tickets_mensagens  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tickets_eventos    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tickets_atendentes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tickets_config     ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tickets_select ON public.tickets;
CREATE POLICY tickets_select ON public.tickets FOR SELECT TO authenticated
USING (public.fn_ticket_visivel(empresa_id, setor_id, aberto_por));

DROP POLICY IF EXISTS tickets_insert ON public.tickets;
CREATE POLICY tickets_insert ON public.tickets FOR INSERT TO authenticated
WITH CHECK (
  public.fn_can_access_empresa(empresa_id)
  AND aberto_por = (SELECT auth.uid())
  AND public.fn_ticket_pode_abrir()
);

-- Um UPDATE so: o recorte fino de "o autor so cancela" vive no gatilho
-- `fn_ticket_guarda_edicao`, porque RLS nao compara coluna a coluna.
DROP POLICY IF EXISTS tickets_update ON public.tickets;
CREATE POLICY tickets_update ON public.tickets FOR UPDATE TO authenticated
USING (
  public.fn_ticket_visivel(empresa_id, setor_id, aberto_por)
  AND (public.fn_ticket_pode_atender() OR aberto_por = (SELECT auth.uid()))
)
WITH CHECK (
  public.fn_ticket_visivel(empresa_id, setor_id, aberto_por)
  AND (public.fn_ticket_pode_atender() OR aberto_por = (SELECT auth.uid()))
);

DROP POLICY IF EXISTS tickets_delete ON public.tickets;
CREATE POLICY tickets_delete ON public.tickets FOR DELETE TO authenticated
USING (public.fn_user_is_super_admin() OR public.fn_user_has_any_role(ARRAY['administrador']));

DROP POLICY IF EXISTS tickets_msg_select ON public.tickets_mensagens;
CREATE POLICY tickets_msg_select ON public.tickets_mensagens FOR SELECT TO authenticated
USING (EXISTS (
  SELECT 1 FROM public.tickets t
   WHERE t.id = ticket_id
     AND public.fn_ticket_visivel(t.empresa_id, t.setor_id, t.aberto_por)
));

DROP POLICY IF EXISTS tickets_msg_insert ON public.tickets_mensagens;
CREATE POLICY tickets_msg_insert ON public.tickets_mensagens FOR INSERT TO authenticated
WITH CHECK (
  autor_id = (SELECT auth.uid())
  AND EXISTS (
    SELECT 1 FROM public.tickets t
     WHERE t.id = ticket_id
       AND public.fn_ticket_visivel(t.empresa_id, t.setor_id, t.aberto_por)
  )
);

DROP POLICY IF EXISTS tickets_ev_select ON public.tickets_eventos;
CREATE POLICY tickets_ev_select ON public.tickets_eventos FOR SELECT TO authenticated
USING (EXISTS (
  SELECT 1 FROM public.tickets t
   WHERE t.id = ticket_id
     AND public.fn_ticket_visivel(t.empresa_id, t.setor_id, t.aberto_por)
));

-- Sem INSERT/UPDATE/DELETE para ninguem: a trilha e escrita pelo gatilho
-- SECURITY DEFINER, que ignora RLS. Uma trilha que o cliente pode reescrever
-- nao serve para resolver discordancia.

DROP POLICY IF EXISTS tickets_atend_select ON public.tickets_atendentes;
CREATE POLICY tickets_atend_select ON public.tickets_atendentes FOR SELECT TO authenticated
USING (public.fn_can_access_empresa(empresa_id));

DROP POLICY IF EXISTS tickets_atend_write ON public.tickets_atendentes;
CREATE POLICY tickets_atend_write ON public.tickets_atendentes FOR ALL TO authenticated
USING (
  public.fn_can_access_empresa(empresa_id)
  AND (public.fn_user_is_super_admin() OR public.fn_user_has_any_role(ARRAY['administrador']))
)
WITH CHECK (
  public.fn_can_access_empresa(empresa_id)
  AND (public.fn_user_is_super_admin() OR public.fn_user_has_any_role(ARRAY['administrador']))
);

-- Todo mundo LE a config: e ela que decide se o item aparece no menu.
DROP POLICY IF EXISTS tickets_config_select ON public.tickets_config;
CREATE POLICY tickets_config_select ON public.tickets_config FOR SELECT TO authenticated
USING (public.fn_can_access_empresa(empresa_id));

DROP POLICY IF EXISTS tickets_config_write ON public.tickets_config;
CREATE POLICY tickets_config_write ON public.tickets_config FOR ALL TO authenticated
USING (
  public.fn_can_access_empresa(empresa_id)
  AND (public.fn_user_is_super_admin() OR public.fn_user_has_any_role(ARRAY['administrador']))
)
WITH CHECK (
  public.fn_can_access_empresa(empresa_id)
  AND (public.fn_user_is_super_admin() OR public.fn_user_has_any_role(ARRAY['administrador']))
);

-- ── Guarda de edicao ────────────────────────────────────────────────────────

/*
 * Quem abriu pode CANCELAR e mais nada.
 *
 * A politica de UPDATE deixa o autor escrever na linha; sem este gatilho ele
 * poderia se marcar como concluido, trocar a categoria depois de resolvido ou
 * se colocar como responsavel. O recorte e por coluna, e RLS nao faz isso.
 */
CREATE OR REPLACE FUNCTION public.fn_ticket_guarda_edicao()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $$
BEGIN
  IF public.fn_ticket_pode_atender() THEN
    RETURN NEW;
  END IF;

  IF OLD.aberto_por <> auth.uid() THEN
    RAISE EXCEPTION 'TICKET_SEM_PERMISSAO: apenas quem atende pode alterar este ticket'
      USING ERRCODE = '42501';
  END IF;

  IF NEW.status <> 'cancelado' OR OLD.status IN ('concluido','recusado','cancelado') THEN
    RAISE EXCEPTION 'TICKET_SEM_PERMISSAO: quem abriu so pode cancelar um ticket ainda em aberto'
      USING ERRCODE = '42501';
  END IF;

  -- Cancelar e mudar UMA coisa. Tudo o mais volta ao que era.
  NEW.numero          := OLD.numero;
  NEW.empresa_id      := OLD.empresa_id;
  NEW.setor_id        := OLD.setor_id;
  NEW.aberto_por      := OLD.aberto_por;
  NEW.aberto_por_nome := OLD.aberto_por_nome;
  NEW.categoria       := OLD.categoria;
  NEW.assunto         := OLD.assunto;
  NEW.descricao       := OLD.descricao;
  NEW.prioridade      := OLD.prioridade;
  NEW.responsavel_id  := OLD.responsavel_id;
  NEW.responsavel_nome:= OLD.responsavel_nome;
  NEW.campos          := OLD.campos;
  NEW.criado_em       := OLD.criado_em;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_ticket_guarda_edicao ON public.tickets;
CREATE TRIGGER trg_ticket_guarda_edicao
BEFORE UPDATE ON public.tickets
FOR EACH ROW EXECUTE FUNCTION public.fn_ticket_guarda_edicao();

CREATE OR REPLACE FUNCTION public.fn_ticket_carimbar()
RETURNS TRIGGER
LANGUAGE plpgsql SET search_path TO 'public'
AS $$
BEGIN
  NEW.atualizado_em := NOW();
  IF NEW.status IN ('concluido','recusado','cancelado')
     AND OLD.status NOT IN ('concluido','recusado','cancelado') THEN
    NEW.fechado_em := NOW();
  ELSIF NEW.status NOT IN ('concluido','recusado','cancelado') THEN
    NEW.fechado_em := NULL;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_ticket_carimbar ON public.tickets;
CREATE TRIGGER trg_ticket_carimbar
BEFORE UPDATE ON public.tickets
FOR EACH ROW EXECUTE FUNCTION public.fn_ticket_carimbar();

-- ── Trilha + notificacao ────────────────────────────────────────────────────

/** Nome de quem esta agindo, para a trilha e para a notificacao. */
CREATE OR REPLACE FUNCTION public.fn_ticket_nome_do_autor()
RETURNS TEXT
LANGUAGE SQL STABLE SECURITY DEFINER SET search_path TO 'public'
AS $$
  SELECT COALESCE(nome, usuario, 'Sistema') FROM public.perfis WHERE id = (SELECT auth.uid());
$$;

/**
 * Uma notificacao por destinatario, pulando quem esta agindo.
 *
 * `p_destinos` chega com nulos e repetidos de proposito — quem chama nao
 * precisa saber se o ticket tem responsavel nem se o autor e o proprio dono.
 */
CREATE OR REPLACE FUNCTION public.fn_ticket_notificar(
  p_empresa_id UUID, p_ticket_id UUID, p_destinos UUID[],
  p_titulo TEXT, p_mensagem TEXT
)
RETURNS VOID
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $$
DECLARE
  v_autor UUID := auth.uid();
  v_nome  TEXT := public.fn_ticket_nome_do_autor();
  v_foto  TEXT;
BEGIN
  SELECT foto_url INTO v_foto FROM public.perfis WHERE id = v_autor;

  INSERT INTO public.notificacoes
    (usuario_id, empresa_id, titulo, mensagem, rota, autor_id, autor_nome, autor_foto)
  SELECT DISTINCT d, p_empresa_id, p_titulo, p_mensagem,
         '/tickets?ticket=' || p_ticket_id::TEXT, v_autor, v_nome, v_foto
    FROM unnest(p_destinos) AS d
   WHERE d IS NOT NULL AND d IS DISTINCT FROM v_autor;
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_ticket_apos_insert()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $$
DECLARE
  v_destinos UUID[];
BEGIN
  INSERT INTO public.tickets_eventos (ticket_id, autor_id, autor_nome, tipo, para)
  VALUES (NEW.id, auth.uid(), public.fn_ticket_nome_do_autor(), 'aberto', NEW.status);

  -- Administradores da empresa + quem foi autorizado a mao. Um ticket sem
  -- ninguem avisado e um ticket que so aparece quando alguem abre a aba.
  SELECT array_agg(id) INTO v_destinos FROM (
    SELECT p.id FROM public.perfis p
     WHERE p.empresa_id = NEW.empresa_id
       AND p.perfil IN ('administrador','super_admin')
       AND COALESCE(p.ativo, TRUE)
    UNION
    SELECT a.perfil_id FROM public.tickets_atendentes a
     WHERE a.empresa_id = NEW.empresa_id
  ) AS alvos;

  PERFORM public.fn_ticket_notificar(
    NEW.empresa_id, NEW.id, v_destinos,
    'Novo ticket #' || NEW.numero,
    COALESCE(NEW.aberto_por_nome, 'Alguem') || ' abriu: ' || NEW.assunto
  );
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_ticket_apos_insert ON public.tickets;
CREATE TRIGGER trg_ticket_apos_insert
AFTER INSERT ON public.tickets
FOR EACH ROW EXECUTE FUNCTION public.fn_ticket_apos_insert();

CREATE OR REPLACE FUNCTION public.fn_ticket_apos_update()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $$
DECLARE
  v_nome TEXT := public.fn_ticket_nome_do_autor();
BEGIN
  IF NEW.status IS DISTINCT FROM OLD.status THEN
    INSERT INTO public.tickets_eventos (ticket_id, autor_id, autor_nome, tipo, de, para)
    VALUES (NEW.id, auth.uid(), v_nome, 'status', OLD.status, NEW.status);

    PERFORM public.fn_ticket_notificar(
      NEW.empresa_id, NEW.id, ARRAY[NEW.aberto_por, NEW.responsavel_id],
      'Ticket #' || NEW.numero || ': ' || NEW.status,
      v_nome || ' mudou o ticket "' || NEW.assunto || '" para ' || NEW.status || '.'
    );
  END IF;

  IF NEW.responsavel_id IS DISTINCT FROM OLD.responsavel_id THEN
    INSERT INTO public.tickets_eventos (ticket_id, autor_id, autor_nome, tipo, de, para)
    VALUES (NEW.id, auth.uid(), v_nome, 'responsavel',
            OLD.responsavel_nome, NEW.responsavel_nome);

    PERFORM public.fn_ticket_notificar(
      NEW.empresa_id, NEW.id, ARRAY[NEW.aberto_por, NEW.responsavel_id],
      'Ticket #' || NEW.numero || ' tem responsavel',
      COALESCE(NEW.responsavel_nome, 'Ninguem') || ' esta cuidando de "' || NEW.assunto || '".'
    );
  END IF;

  IF NEW.prioridade IS DISTINCT FROM OLD.prioridade THEN
    INSERT INTO public.tickets_eventos (ticket_id, autor_id, autor_nome, tipo, de, para)
    VALUES (NEW.id, auth.uid(), v_nome, 'prioridade', OLD.prioridade, NEW.prioridade);
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_ticket_apos_update ON public.tickets;
CREATE TRIGGER trg_ticket_apos_update
AFTER UPDATE ON public.tickets
FOR EACH ROW EXECUTE FUNCTION public.fn_ticket_apos_update();

CREATE OR REPLACE FUNCTION public.fn_ticket_apos_mensagem()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $$
DECLARE
  t public.tickets%ROWTYPE;
BEGIN
  SELECT * INTO t FROM public.tickets WHERE id = NEW.ticket_id;
  IF NOT FOUND THEN RETURN NEW; END IF;

  -- So quem abriu e quem assumiu. O restante da lideranca do setor ve o ticket
  -- na aba; notificar todos eles transformaria a campainha em ruido de fundo,
  -- e ai ninguem olha nenhuma.
  PERFORM public.fn_ticket_notificar(
    t.empresa_id, t.id, ARRAY[t.aberto_por, t.responsavel_id],
    'Ticket #' || t.numero || ': nova mensagem',
    COALESCE(NEW.autor_nome, 'Alguem') || ': '
      || LEFT(COALESCE(NULLIF(TRIM(NEW.texto), ''), '[anexo]'), 120)
  );

  UPDATE public.tickets SET atualizado_em = NOW() WHERE id = NEW.ticket_id;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_ticket_apos_mensagem ON public.tickets_mensagens;
CREATE TRIGGER trg_ticket_apos_mensagem
AFTER INSERT ON public.tickets_mensagens
FOR EACH ROW EXECUTE FUNCTION public.fn_ticket_apos_mensagem();

-- ── Anexos ──────────────────────────────────────────────────────────────────

-- Bucket publico como `perfis` e `comemoracoes`: o caminho carrega um UUID
-- aleatorio, e o que entra aqui e print de tela do proprio sistema. 15 MB
-- cobre print, foto de celular e audio curto.
INSERT INTO storage.buckets (id, name, public, file_size_limit)
VALUES ('tickets', 'tickets', TRUE, 15728640)
ON CONFLICT (id) DO UPDATE SET public = TRUE, file_size_limit = 15728640;

DROP POLICY IF EXISTS tickets_anexo_read ON storage.objects;
CREATE POLICY tickets_anexo_read ON storage.objects FOR SELECT
USING (bucket_id = 'tickets');

DROP POLICY IF EXISTS tickets_anexo_write ON storage.objects;
CREATE POLICY tickets_anexo_write ON storage.objects FOR INSERT TO authenticated
WITH CHECK (bucket_id = 'tickets');

DROP POLICY IF EXISTS tickets_anexo_delete ON storage.objects;
CREATE POLICY tickets_anexo_delete ON storage.objects FOR DELETE TO authenticated
USING (bucket_id = 'tickets' AND owner = (SELECT auth.uid()));

-- ── Permissoes ──────────────────────────────────────────────────────────────

GRANT SELECT, INSERT, UPDATE, DELETE ON public.tickets            TO authenticated;
GRANT SELECT, INSERT                 ON public.tickets_mensagens  TO authenticated;
GRANT SELECT                         ON public.tickets_eventos    TO authenticated;
GRANT SELECT, INSERT, DELETE         ON public.tickets_atendentes TO authenticated;
GRANT SELECT, INSERT, UPDATE         ON public.tickets_config     TO authenticated;

-- `anon` nao tem o que fazer aqui — mesma faxina da 20260818240000.
REVOKE ALL ON public.tickets, public.tickets_mensagens, public.tickets_eventos,
             public.tickets_atendentes, public.tickets_config FROM anon;

REVOKE ALL ON FUNCTION public.fn_ticket_pode_atender()               FROM anon, public;
REVOKE ALL ON FUNCTION public.fn_ticket_pode_abrir()                 FROM anon, public;
REVOKE ALL ON FUNCTION public.fn_ticket_visivel(UUID, UUID, UUID)    FROM anon, public;
REVOKE ALL ON FUNCTION public.fn_ticket_notificar(UUID, UUID, UUID[], TEXT, TEXT) FROM anon, public;
REVOKE ALL ON FUNCTION public.fn_ticket_nome_do_autor()              FROM anon, public;

GRANT EXECUTE ON FUNCTION public.fn_ticket_pode_atender()            TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_ticket_pode_abrir()              TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_ticket_visivel(UUID, UUID, UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_ticket_nome_do_autor()           TO authenticated;
